{{- if and .Values.networkPolicy.enabled .Values.service.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "landing.fullname" . }}
  labels:
    {{- include "landing.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "landing.selectorLabels" . | nindent 6 }}
  ingress:
    - ports:
        - protocol: "TCP"
          port: {{ .Values.service.port }}
  policyTypes:
    - Ingress
{{- end }}
