---
apiVersion: v2
name: wardend
description: A chart to deploy Wardend to Kubernetes

type: application

version: 2.11.0

appVersion: "v0.5.2"
maintainers:
  - name: jlehtimaki
    email: joonas@wardenprotocol.org
    url: https://github.com/jlehtimaki
  - name: zavertiaev
    url: https://github.com/zavertiaev
  - name: mikolajsobolewski
    url: https://github.com/mikolajsobolewski
