# Default values for deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image: ghcr.io/open-custody/keychain-operators/blockchain-listener
imagePullPolicy: IfNotPresent
imageTag: ""
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  enabled: true
  type: ClusterIP
  port: 3000
  # targetport - dafault as port

resources:
  requests:
    cpu: 20m
    memory: 64Mi
  limits:
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

extraEnv: []
envFrom: ""

secretManager:
  enabled: false
  serviceAccount:
    create: false
    name: ""
    annotations: {}
  secrets: []
  pullSecrets: []
  cmd: "yarn blockchain-listener"
