---
apiVersion: v2
name: hermes-relayer
description: A Helm chart for Kubernetes
type: application
version: 0.4.0
maintainers:
  - name: "zavertiaev"
  - name: "jlehtimaki"
  - name: "mikolajsobolewski"
appVersion: 1.12.0
