{{- if and .Values.networkPolicy.enabled .Values.service.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "main.fullname" . }}
  labels:
    {{- include "main.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "main.selectorLabels" . | nindent 6 }}
  ingress:
    - ports:
      {{- range .Values.service.ports }}
        - protocol: {{ .protocol | default "TCP" }}
          port: {{ .port }}
      {{- end }}
      {{- if .Values.networkPolicy.ingress.namespaceSelector }}
      from:
        - namespaceSelector:
          {{- toYaml .Values.networkPolicy.ingress.namespaceSelector | nindent 12 }}
          {{- if .Values.networkPolicy.ingress.podSelector }}
          podSelector:
          {{- toYaml .Values.networkPolicy.ingress.podSelector | nindent 12 }}
          {{- end }}
      {{- end }}
  policyTypes:
    - Ingress
{{- end }}
