{{- if .Values.secretManager.enabled }}
{{- $values := .Values }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "main.fullname" . }}
  labels:
    {{- include "main.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    objects: |
    {{- range .Values.secretManager.secrets }}
    {{- if $values.secretManager.cmd }}
      - objectName: "{{ . }}"
        objectType: "secretsmanager"
    {{- else }}
      - objectName: "{{ .objectName }}"
        objectType: "secretsmanager"
        jmesPath: 
        {{- range .jmesPath }}
          - path: {{ .path }}
            objectAlias: {{ .objectAlias }}
        {{- end }}
    {{- end }}
    {{- end }}
    {{- with .Values.secretManager.pullSecrets }}
    {{- range $index, $secret := . }}
      - objectName: "{{ $secret }}"
        objectType: "secretsmanager"
        objectAlias: "{{ (index $.Values.imagePullSecrets $index).name }}"
    {{- end }}
    {{- end }}
  {{- with .Values.secretManager.pullSecrets }}
  secretObjects:
  {{- range $index, $secret := . }}
    - secretName: "{{ (index $.Values.imagePullSecrets $index).name }}"
      type: "kubernetes.io/dockerconfigjson"
      data:
        - objectName: "{{ (index $.Values.imagePullSecrets $index).name }}"
          key: ".dockerconfigjson"
  {{- end }}
  {{- end }}
{{- end }}
