{{- if .Values.node.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.node.name }}
  labels:
  {{- include "node.labels" . | nindent 4}}
  annotations: 
  {{- include "node.externalDNS" . |nindent 4}}
  {{- with .Values.node.ingress.annotations }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.node.ingress.class }}
  rules:
    {{- if .Values.node.rpc.enabled }}
    - host: rpc.{{ .Values.node.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.node.name }}-http
                port:
                  number: 26657
            path: /
            pathType: {{ .Values.node.ingress.pathType }}
    {{- end}}
    {{- if .Values.node.api.enabled }}
    - host: api.{{ .Values.node.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.node.name }}-http
                port:
                  number: 1317
            path: /
            pathType: {{ .Values.node.ingress.pathType }}
    {{- end}}
    {{- if .Values.evm.rpc }}
    - host: evm.{{ .Values.node.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.node.name }}-http
                port:
                  number: 8545
            path: /
            pathType: {{ .Values.node.ingress.pathType }}
    - host: evm-ws.{{ .Values.node.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.node.name }}-http
                port:
                  number: 8546
            path: /
            pathType: {{ .Values.node.ingress.pathType }}
    {{- end}}
  tls:
  {{- if .Values.node.rpc.enabled }}
  - hosts:
    - rpc.{{ .Values.node.ingress.host }}
    secretName: {{ .Release.Name }}-{{ .Values.node.name }}-rpc-tls
  {{- end }}
  {{- if .Values.node.api.enabled }}
  - hosts:
    - api.{{ .Values.node.ingress.host }}
    secretName: {{ .Release.Name }}-{{ .Values.node.name }}-api-tls
  {{- end}}
  {{- if .Values.evm.rpc }}
  - hosts:
    - evm.{{ .Values.node.ingress.host }}
    secretName: {{ .Release.Name }}-{{ .Values.node.name }}-evm-tls
  - hosts:
    - evm-ws.{{ .Values.node.ingress.host }}
    secretName: {{ .Release.Name }}-{{ .Values.node.name }}-evm-ws-tls
  {{- end }}
{{- end}}
