{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-{{ .Values.node.name }}
  labels:
    {{- include "node.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "node.selectorLabels" . | nindent 6 }}
  ingress:
    - ports:
        {{- if .Values.node.rpc.enabled }}
        - protocol: TCP
          port: 26657
        {{- end }}
        {{- if .Values.node.p2p.enabled }}
        - protocol: TCP
          port: 26656
        {{- end }}
        {{- if .Values.node.api.enabled }}
        - protocol: TCP
          port: 1317
        {{- end }}
        {{- if .Values.node.grpc.enabled}}
        - protocol: TCP
          port: 9090
        {{- end }}
        {{- if .Values.node.externalSigner }}
        - protocol: TCP
          port: 1234
        {{- end }}
        {{- if .Values.node.metrics.enabled }}
        - protocol: TCP
          port: 26660
        {{- if .Values.oracle.metricsEnabled }}
        - protocol: TCP
          port: 8002
        {{- end }}
        {{- end }}
  policyTypes:
    - Ingress
{{- end }}
