---
{{- if .Values.node.metrics.enabled }}
{{- $values := .Values }}
{{- range $i, $e := until (int .Values.node.replicaCount)}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "node.name" $ }}-{{ $i }}
  labels:
    statefulset.kubernetes.io/pod-name: {{ include "node.name" $ }}-{{ $i }}
    {{- include "node.selectorLabels" $ | nindent 4 }}
    {{- include "serviceMonitor.extraLabels" $ | nindent 4 }}
spec:
  jobLabel: {{ include "node.name" $ }}-{{ $i }}
  selector:
    matchLabels:
        statefulset.kubernetes.io/pod-name: {{ include "node.name" $ }}-{{ $i }}
  endpoints:
    - port: telemetry
      path: /metrics
      interval: {{ $values.serviceMonitor.telemetry.interval }}
      scrapeTimeout: {{ $values.serviceMonitor.telemetry.scrapeTimeout }}
    {{- if $values.oracle.metricsEnabled }}
    - port: oracle-metrics
      path: /metrics
      interval: {{ $values.serviceMonitor.oracle.interval }}
      scrapeTimeout: {{ $values.serviceMonitor.oracle.scrapeTimeout }}
    {{- end }}
    {{- if $values.evm.metrics }}
    - port: evm-metrics
      path: /debug/metrics/prometheus
      interval: {{ $values.serviceMonitor.evm.interval }}
      scrapeTimeout: {{ $values.serviceMonitor.evm.scrapeTimeout }}
    {{- end }}
---
{{- end}}
{{- end}}
