---
{{- if .Values.node.metrics.enabled }}
{{- $values := .Values }}
{{- range $i, $e := until (int .Values.node.replicaCount)}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "node.name" $ }}-{{ $i }}
  labels:
    statefulset.kubernetes.io/pod-name: {{ include "node.name" $ }}-{{ $i }}
    {{- include "node.selectorLabels" $ | nindent 4 }}
    {{- include "serviceMonitor.extraLabels" $ | nindent 4 }}
spec:
  jobLabel: {{ include "node.name" $ }}-{{ $i }}
  selector:
    matchLabels:
        statefulset.kubernetes.io/pod-name: {{ include "node.name" $ }}-{{ $i }}
  endpoints:
    {{- if $values.node.metrics.serviceMonitor.enabled }}
    - port: telemetry
      path: /metrics
      interval: {{ $values.node.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ $values.node.metrics.serviceMonitor.scrapeTimeout }}
    {{- end }}
    {{- if and $values.oracle.metrics.enabled $values.oracle.metrics.serviceMonitor.enabled }}
    - port: oracle-metrics
      path: /metrics
      interval: {{ $values.oracle.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ $values.oracle.metrics.serviceMonitor.scrapeTimeout }}
    {{- end }}
    {{- if and $values.evm.metrics.enabled $values.evm.metrics.serviceMonitor.enabled }}
    - port: evm-metrics
      path: /debug/metrics/prometheus
      interval: {{ $values.evm.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ $values.evm.metrics.serviceMonitor.scrapeTimeout }}
    {{- end }}
---
{{- end}}
{{- end}}
