---
apiVersion: v2
name: discord-faucet
description: A Helm chart for Discord Faucet
type: application
version: 0.4.1
appVersion: 1.2.0
maintainers:
  - name: jlehtimaki
    email: joonas@wardenprotocol.org
    url: https://github.com/jlehtimaki
  - name: zavertiaev
    url: https://github.com/zavertiaev
