---
image: ghcr.io/warden-protocol/discord-faucet
imagePullPolicy: IfNotPresent
tag: ""

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false

# env:
# envFrom: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

service:
  type: ClusterIP
  port: 8081

serviceMonitor:
  enabled: false
  additionalLabels: {}
  interval: 1m
  scrapeTimeout: 10s
  telemetryPath: /metrics
  targetLabels: []
  metricRelabelings: []
  relabelings: []

logLevel: info

secretManager:
  enabled: false
  serviceAccount:
    create: false
    name: ""
    annotations: {}
  secrets: []

networkPolicy:
  enabled: true
  metrics:
    podSelector: {}
    namespaceSelector: {}
