{{- if and .Values.networkPolicy.enabled .Values.service.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "faucet.fullname" . }}
  labels:
    {{- include "faucet.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "faucet.selectorLabels" . | nindent 6 }}
  ingress:
    - ports:
      {{- range .Values.service.ports }}
        - protocol: TCP
          port: {{ .port }}
      {{- end }}
  policyTypes:
    - Ingress
{{- end }}