{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "discord-faucet.fullname" . }}
  labels:
    {{- include "discord-faucet.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "discord-faucet.selectorLabels" . | nindent 6 }}
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  policyTypes:
    - Ingress
{{- end }}
