{{- if .Values.secretManager.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "hermes-relayer.fullname" . }}
  labels:
    {{- include "hermes-relayer.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    objects: |
    {{- range .Values.secretManager.secrets }}
        - objectName: "{{ .objectName }}"
          objectType: "secretsmanager"
          jmesPath: 
          {{- range .jmesPath }}
            - path: {{ .path }}
              objectAlias: {{ .objectAlias }}
          {{- end }}
    {{- end }}
{{- end }}
