{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "name" . }}
  labels:
    {{- include "selectorLabels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  ingress:
    - ports:
        - protocol: TCP
          port: 2222
      from:
        - podSelector: {}
    {{- if .Values.metrics.enabled }}
    - ports:
        - protocol: TCP
          port: 6001
      {{- if .Values.networkPolicy.metrics.namespaceSelector }}
      from:
        - namespaceSelector:
          {{- toYaml .Values.networkPolicy.metrics.namespaceSelector | nindent 12 }}
          {{- if .Values.networkPolicy.metrics.podSelector }}
          podSelector:
          {{- toYaml .Values.networkPolicy.metrics.podSelector | nindent 12 }}
          {{- end }}
      {{- end }}
    {{- end}}
  policyTypes:
    - Ingress
{{- end }}
