apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "landing-webhook.fullname" . }}
  labels:
    {{- include "landing-webhook.labels" . | nindent 4}}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: [{{ .Values.targetResourceName | quote }}]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "landing-webhook.fullname" . }}
  labels:
    {{- include "landing-webhook.labels" . | nindent 4}}
subjects:
  - kind: ServiceAccount
    name: {{ include "landing-webhook.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "landing-webhook.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
