---
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: {{ include "landing-webhook.fullname" . }}
spec:
  nats:
    native:
      replicas: {{ .Values.eventBus.replicas }}
      auth: token
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ include "landing-webhook.fullname" . }}
  labels:
    eventsource-name: {{ include "landing-webhook.fullname" . }}
spec:
  {{- .Values.eventSource.name | nindent 2 }}:
    {{- .Values.eventSource.eventName | nindent 4 }}:
      port: {{ .Values.service.port }}
      endpoint: {{ .Values.eventSource.endpoint }}
      method: {{ .Values.eventSource.method }}
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ include "landing-webhook.fullname" . }}
  labels:
    {{- include "landing-webhook.labels" . | nindent 4 }}
spec:
  template:
    serviceAccountName: {{ include "landing-webhook.fullname" . }}
  dependencies:
    - name: {{ .Values.eventSource.name }}
      eventSourceName: {{ include "landing-webhook.fullname" . }}
      eventName: {{ .Values.eventSource.eventName }}
  triggers:
    - template:{{ .Values.sensor.template | toYaml | nindent 8 }}