apiVersion: v1
kind: Service
metadata:
  name: {{ include "landing-webhook.fullname" . }}
  labels:
    {{- include "landing-webhook.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport | default .Values.service.port }}
      protocol: TCP
  selector:
    eventsource-name: {{ include "landing-webhook.fullname" . }}
